SELECT *
FROM CAR_INFO;
-- 메인 페이지 

-- CREATE 

INSERT INTO `retoree`.`car_info` (`CAR_ID`, `MUNUFACTURER`, `MODEL`, `DETAILED_MODEL`, `VEH_NUM`, `PRICE`, `MODEL_YEAR`, `FUEL`, `TRANSMISSION`, `CARGRADE`, `DETAILED_CARGRADE`, `DRIVEN_DIST`, `ACCIDENT_INFO`, `OPTIONS`, `COLOR`, `DTL_IMG_CAR`, `SALE_STATUS`, `PANER_ID`, `SKELETON_ID`)
 VALUES ('C01', '현대', '엑센트', '신형 모던 wit 1.4 VVT', '12가3456', '750', '2015', '가솔린', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'P01', 'S01');
INSERT INTO `retoree`.`car_info` (`CAR_ID`, `MUNUFACTURER`, `MODEL`, `DETAILED_MODEL`, `VEH_NUM`, `PRICE`, `MODEL_YEAR`, `FUEL`, `TRANSMISSION`, `CARGRADE`, `DETAILED_CARGRADE`, `DRIVEN_DIST`, `ACCIDENT_INFO`, `OPTIONS`, `COLOR`, `DTL_IMG_CAR`, `SALE_STATUS`, `PANER_ID`, `SKELETON_ID`) 
VALUES ('C02', '현대', '캐스퍼', '가솔린 1.0 인스퍼레이션', '34나5678', '1770', '2022', '가솔린', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'P02', 'S02');

INSERT INTO `retoree`.`CAR_INFO` (`CAR_ID`, `ORIGIN`, `MUNUFACTURER`, `MODEL`, `DETAILED_MODEL`, `VEH_NUM`, `PRICE`, `MODEL_YEAR`, `FUEL`, `ADDR_CITY`, `TRANSMISSION`, `CARGRADE`, `DETAILED_CARGRADE`, `DRIVEN_DIST`, `ACCIDENT_INFO`, `OPTIONS`, `COLOR`, `DTL_IMG_CAR`, `SALE_STATUS`, `PANER_ID`, `SKELETON_ID`)
 VALUES ('C03', '수입', '벤츠', 'E-클래스 ', 'W213', '56다0987', '4800', '2019', '디젤', '순천', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'P01', 'S02');

ALTER TABLE CAR_INFO ADD ADDR_CITY VARCHAR(100) NULL DEFAULT'0'; -- 지역 컬럼 추가

ALTER TABLE CAR_INFO ADD ORIGIN VARCHAR(100) NULL; -- 국산/수입 구분 컬럼 추가

ALTER TABLE `retoree`.`car_info` 
CHANGE COLUMN `ORIGIN` `ORIGIN` VARCHAR(100) NULL DEFAULT NULL AFTER `CAR_ID`, -- 컬럼 자리 변경
CHANGE COLUMN `ADDR_CITY` `ADDR_CITY` VARCHAR(100) NULL DEFAULT '0' AFTER `FUEL`; -- 컬럼 자리 변경

-- READ
-- 검색
SELECT MUNUFACTURER, MODEL, DETAILED_MODEL
FROM CAR_INFO;

-- 메인 페이지 차량

-- 특가
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE PRICE < 1000
;

-- 신차급
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE MODEL_YEAR = '2022'
;

-- 인기 국산차
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE ORIGIN = '국산'
;

-- 인기 수입차
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE ORIGIN = '수입'
;
 
-- UPDATE
UPDATE CAR_INFO
SET ADDR_CITY = '부산' -- 지역 추가
WHERE CAR_ID = 'C02';

UPDATE `retoree`.`CAR_INFO`
 SET `ORIGIN` = '국산' 
 WHERE (`CAR_ID` = 'C01');
UPDATE `retoree`.`CAR_INFO` 
SET `ORIGIN` = '국산'
 WHERE (`CAR_ID` = 'C02');


-- DELETE
DELETE FROM CAR_INFO
WHERE CAR_ID = 'C01';