
-- 메인 페이지 

-- CREATE 

INSERT INTO `retoree`.`car_info` (`CAR_ID`, `MUNUFACTURER`, `MODEL`, `DETAILED_MODEL`, `VEH_NUM`, `PRICE`, `MODEL_YEAR`, `FUEL`, `TRANSMISSION`, `CARGRADE`, `DETAILED_CARGRADE`, `DRIVEN_DIST`, `ACCIDENT_INFO`, `OPTIONS`, `COLOR`, `DTL_IMG_CAR`, `SALE_STATUS`, `PANER_ID`, `SKELETON_ID`)
 VALUES ('C01', '현대', '엑센트', '엑센트 신형 모던 wit 1.4 VVT', '12가3456', '750', '2015', '가솔린', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'P01', 'S01');
INSERT INTO `retoree`.`car_info` (`CAR_ID`, `MUNUFACTURER`, `MODEL`, `DETAILED_MODEL`, `VEH_NUM`, `PRICE`, `MODEL_YEAR`, `FUEL`, `TRANSMISSION`, `CARGRADE`, `DETAILED_CARGRADE`, `DRIVEN_DIST`, `ACCIDENT_INFO`, `OPTIONS`, `COLOR`, `DTL_IMG_CAR`, `SALE_STATUS`, `PANER_ID`, `SKELETON_ID`) 
VALUES ('C02', '현대', '캐스퍼', '캐스퍼 가솔린 1.0 인스퍼레이션', '34나5678', '1770', '2022', '가솔린', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'P02', 'S02');

ALTER TABLE CAR_INFO ADD ADDR_CITY VARCHAR(100) NULL DEFAULT'0'; -- 테이블 컬럼 추가

-- READ
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO;
 
-- UPDATE
UPDATE CAR_INFO
SET ADDR_CITY = '부산' -- 가격 변경
WHERE CAR_ID = 'C02';

-- DELETE
DELETE FROM CAR_INFO
WHERE CAR_ID = 'C01';