INSERT INTO REGISTER_AGREE
(TS_CS_ID, TS_CS, PER_INF_REQ, PER_INF_OPT, REGULATION, REC_MKT_INF)
VALUES
('R01', 'YES', 'YES', 'YES', 'YES', 'YES'),
('R02', 'YES', 'YES', 'NO', 'YES', 'NO'),
('R03', 'YES', 'YES', 'NO', 'YES', 'NO')
;

-- READ
SELECT TS_CS_ID, TS_CS, PER_INF_REQ, PER_INF_OPT, REGULATION, REC_MKT_INF
FROM REGISTER_AGREE
;

-- UPDATE
UPDATE REGISTER_AGREE
SET REC_MKT_INF ='YES'
WHERE TS_CS_ID = 'R03'
;

-- DELETE
DELETE FROM REGISTER_AGREE
WHERE TS_CS_ID = 'R03'
;
