
CREATE TABLE REGISTER_1
(
  UNIQUE_ID   VARCHAR(200) NOT NULL COMMENT 'UID',
  TS_CS       VARCHAR(200) NULL     COMMENT '이용약관',
  PER_INF_REQ VARCHAR(200) NULL     COMMENT '개인정보 필수 약관',
  PER_INF_OPT VARCHAR(200) NULL     COMMENT '개인정보 선택 약관',
  REGULATION  VARCHAR(200) NULL     COMMENT '리투리 규정 약관',
  REC_MKT_INF VARCHAR(200) NULL     COMMENT '마케팅 정보 수신 동의',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '약관동의';

CREATE TABLE REGISTER_2
(
  UNIQUE_ID     VARCHAR(200) NOT NULL COMMENT 'UID',
  NAME          VARCHAR(200) NULL     COMMENT '이름',
  BIRTHDAY      INT          NULL     COMMENT '생년월일',
  ID            VARCHAR(200) NULL     COMMENT '아이디',
  PASSWORD      VARCHAR(200) NULL     COMMENT '비밀번호',
  CELL_NUMBER   INT          NULL     COMMENT '전화번호',
  EMAIL         VARCHAR(200) NULL     COMMENT '이메일',
  ADDR_CITY     VARCHAR(200) NULL     COMMENT '거주지(시도)',
  ADDR_DISTRICT VARCHAR(200) NULL     COMMENT '거주지(시군구)',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '정보입력';
