
-- CONTACT
SELECT INQ_TITLE, INQ_CONTENT, INQ_DATE, ANS_CONTENT, ANS_DATE, STATUS
FROM CONTACT
JOIN ANSWER_STATUS
ON CONTACT.STATUS_ID = ANSWER_STATUS.STATUS_ID
;

DELETE
FROM CONTACT
WHERE CONTACT_ID = 'CT001'
;


-- 상세정보 페이지
-- 선택된 차량 UID 찾기
SELECT CAR_DTL_ID
FROM CAR_DETAILE_INFO
WHERE CAR_DETAILE_INFO.CAR_DTL_ID = 'C001'
;

-- 선택된 차량을 판매하는 딜러 정보 조회(이름, 전화번호, 프로필)
SELECT USER_INFO.NAME, USER_INFO.CELL_NUMBER, DEALER_INFO.PROFILE_IMG, DEALER_INFO.DEALER_ID
FROM DEALER_INFO
JOIN CAR_DETAILE_INFO
ON CAR_DETAILE_INFO.DEALER_ID = DEALER_INFO.DEALER_ID
JOIN USER_INFO
ON DEALER_INFO.DEALER_ID = USER_INFO.USER_ID
WHERE CAR_DETAILE_INFO.CAR_DTL_ID = 'C001'
;

-- 딜러 차량 판매 수 조회
SELECT COUNT(*)
FROM CAR_DETAILE_INFO
JOIN SALE_STATUS
ON CAR_DETAILE_INFO.STATUS_ID = SALE_STATUS.STATUS_ID
WHERE DEALER_ID = 'U002'
AND STATUS = 'sale'
;

-- 딜러 차량 판매완료 수 조회
SELECT COUNT(*)
FROM CAR_DETAILE_INFO
JOIN SALE_STATUS
ON CAR_DETAILE_INFO.STATUS_ID = SALE_STATUS.STATUS_ID
WHERE DEALER_ID = 'U002'
AND STATUS = 'soldout'
;

-- 선택된 차량 정보 조회
SELECT CAR_INFO.CAR_ID, VEH_NUM, MODEL_YEAR, DRIVEN_DIST, TRANSMISSION, PRICE, DTL_IMG_CAR
FROM CAR_INFO
JOIN CAR_DETAILE_INFO
ON CAR_INFO.CAR_ID = CAR_DETAILE_INFO.CAR_ID
WHERE CAR_DTL_ID = 'C001'
;

-- 선택된 차량 외부 패널 정보 조회
SELECT HOOD, FRONT_FENDER, DOOR, SIDE_PANEL, TRUNK_LID, ROOF_PANEL, QUARTER_PANEL
FROM CAR_PANEL
JOIN CAR_INFO
ON CAR_INFO.PANER_ID = CAR_PANEL.PANER_ID
WHERE CAR_INFO.CAR_ID = 'CAR01'
;

-- 선택된 차량 주요 골격 정보 조회
SELECT FRONT_PANEL, CROSS_MEMBER, INSIDE_PANEL, SIDE_MEMBER, WHEEL_HOUSE, PACKAGE_TRAY, DASH_PANEL, FLOOR_PANEL, FILER_PANEL, REAR_PANEL, TRUNK_FLOOR
FROM CAR_MAIN_SKELETON
JOIN CAR_INFO
ON CAR_INFO.SKELETON_ID = CAR_MAIN_SKELETON.SKELETON_ID
WHERE CAR_INFO.CAR_ID = 'CAR01'
;

-- 찜

DELETE
FROM WISHLIST
WHERE CAR_DTL_ID = 'C001'
;

SELECT *
FROM WISHLIST
;

-- 방문 예약
SELECT RSV_DATE, RSV_STATUS
FROM RESERVATION
WHERE CAR_DTL_ID = 'C001'
;

DELETE
FROM RESERVATION
WHERE CAR_DTL_ID = 'C001'
;

SELECT *
FROM RESERVATION
;

-- 메인 페이지 차량

-- 특가
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE PRICE < 1000
;

-- 신차급
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE MODEL_YEAR = '2022'
;

-- 인기 국산차
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE ORIGIN = '국산'
;

-- 인기 수입차
SELECT CAR_ID, MUNUFACTURER, MODEL, DETAILED_MODEL, PRICE, MODEL_YEAR, FUEL, DRIVEN_DIST, DTL_IMG_CAR, ADDR_CITY, PANER_ID, SKELETON_ID
FROM CAR_INFO
WHERE ORIGIN = '수입'
;

