
CREATE TABLE DEALER_INFO_MODIFY
(
  UNIQUE_ID     VARCHAR(200) NOT NULL COMMENT 'UID',
  PROFILE_IMG   VARCHAR(200) NULL     COMMENT '프로필 이미지',
  NANE          VARCHAR(200) NULL     COMMENT '이름',
  BR_NUMBER     VARCHAR(200) NULL     COMMENT '사업자등록번호',
  ID            VARCHAR(200) NULL     COMMENT '아이디',
  PASSWORD      VARCHAR(200) NULL     COMMENT '비밀번호',
  CELL_NUMBER   INT          NULL     COMMENT '전화번호',
  EMAIL         VARCHAR(200) NULL     COMMENT '이메일',
  ADDR_CITY     VARCHAR(200) NULL     COMMENT '주소(시도)',
  ADDR_DISTRICT VARCHAR(200) NULL     COMMENT '주소(시군구)',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '딜러 정보 수정';
