
CREATE TABLE PRICE_CHECK
(
  UNIQUE_ID         VARCHAR(200) NOT NULL COMMENT 'UID',
  MANUFACTURER      VARCHAR(200) NULL     COMMENT '제조사',
  MODEL             VARCHAR(200) NULL     COMMENT '모델',
  DETAILED_MODEL    VARCHAR(200) NULL     COMMENT '상세모델',
  MODEL_YEAR        VARCHAR(200) NULL     COMMENT '연식',
  FUEL              VARCHAR(200) NULL     COMMENT '연료',
  CARGRADE          VARCHAR(200) NULL     COMMENT '차량등급',
  DETAILED_CARGRADE VARCHAR(200) NULL     COMMENT '세부등급',
  DRIVEN_DIST       INT          NULL     COMMENT '주행거리',
  ACCIDENT_INFO     VARCHAR(200) NULL     COMMENT '사고정보',
  OPTIONS           VARCHAR(200) NULL     COMMENT '추가옵션',
  COLOR             VARCHAR(200) NULL     COMMENT '색상',
  PRICE             INT          NULL     COMMENT '시세',
  DTL_IMG_CAR       VARCHAR(200) NULL     COMMENT '차량 이미지',
  ADDRESS           VARCHAR(200) NULL     COMMENT '지역',
  SALES_COM         VARCHAR(200) NULL     COMMENT '판매완료',
  SALES_PERF        INT          NULL     COMMENT '판매수',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '시세 조회 페이지 테이블';
