-- dealer sales mgmt : 판매관리 페이지
-- DEALER_ID 받아서 조회하기 

-- 딜러 이름 조회
SELECT NAME
FROM DEALER_INFO
JOIN USER_INFO
ON DEALER_ID = USER_ID
WHERE DEALER_ID = 'U001'
;

-- 판매중 차량 조회
SELECT MANUFACTURER, MODEL, VEH_NUM, STATUS, CAR_DETAILE_INFO.CAR_DTL_ID
FROM CAR_DETAILE_INFO
JOIN CAR_INFO
ON CAR_DETAILE_INFO.CAR_ID = CAR_INFO.CAR_ID
JOIN SALE_STATUS
ON CAR_DETAILE_INFO.STATUS_ID = SALE_STATUS.STATUS_ID
WHERE STATUS = 'sale'
AND DEALER_ID = 'U002'
;

-- 판매완료 차량 조회
SELECT SALE_DATE, MANUFACTURER, MODEL, PRICE, CAR_DETAILE_INFO.CAR_DTL_ID
FROM CAR_DETAILE_INFO
JOIN SALE_STATUS
ON CAR_DETAILE_INFO.STATUS_ID = SALE_STATUS.STATUS_ID
JOIN CAR_INFO
ON CAR_DETAILE_INFO.CAR_ID = CAR_INFO.CAR_ID
WHERE STATUS = 'soldout'
AND DEALER_ID = 'U002'
;