
CREATE TABLE DEALER_CUSTOM_CAREPAGE
(
  UNIQUE_ID   VARCHAR(200) NOT NULL COMMENT 'UID',
  INQ_TITLE   VARCHAR(200) NULL     COMMENT '문의 제목',
  INQ_CONTENT VARCHAR(200) NULL     COMMENT '문의 내용',
  USER_ID     VARCHAR(200) NULL     COMMENT '고객 아이디',
  INQ_DATE    VARCHAR(200) NULL     COMMENT '문의 등록일',
  ANS_CONTENT VARCHAR(200) NULL     COMMENT '답변 내용',
  ANS_DATE    VARCHAR(200) NULL     COMMENT '답변 등록일',
  ANS_STATUS  VARCHAR(200) NULL     COMMENT '답변 상태',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '딜러 고객 관리';
