
CREATE TABLE DEALER_MAIN
(
  UNIQUE_ID      VARCHAR(200) NOT NULL COMMENT 'UID',
  NAME           VARCHAR(200) NULL     COMMENT '이름',
  CELL_NUMBER    INT          NULL     COMMENT '전화번호',
  EMAIL          VARCHAR(200) NULL     COMMENT '이메일',
  ADDR_CITY      VARCHAR(200) NULL     COMMENT '주소(시도)',
  ADDR_DISTRICT  VARCHAR(200) NULL     COMMENT '주소(시군구)',
  DETAILED_MODEL VARCHAR(200) NULL     COMMENT '상세모델',
  VEH_NUM        VARCHAR(200) NULL     COMMENT '차량번호',
  DTL_IMG_CAR    VARCHAR(200) NULL     COMMENT '차량 이미지',
  PRICE          INT          NULL     COMMENT '가격',
  QUESTION_TITLE VARCHAR(200) NULL     COMMENT '1:1상담 제목',
  USERID         VARCHAR(200) NULL     COMMENT '고객 아이디',
  QUESTION_DATE  VARCHAR(200) NULL     COMMENT '1:1 상담 작성일',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '딜러 메인페이지';
