
CREATE TABLE CAR_DETAIL_INFO
(
  CAR_DTL_UID    VARCHAR(200) NOT NULL COMMENT '차량 아이디',
  MODEL          VARCHAR(200) NOT NULL COMMENT '모델',
  MODEL_YEAR     VARCHAR(200) NOT NULL COMMENT '연식',
  DRIVEN_DIST    VARCHAR(200) NOT NULL COMMENT '주행거리',
  TRANSMISSION   VARCHAR(200) NOT NULL COMMENT '변속기',
  PRICE          VARCHAR(200) NOT NULL COMMENT '가격',
  DTL_IMG_CAR    VARCHAR(200) NOT NULL COMMENT '차량 이미지',
  DEALER_NAME    VARCHAR(200) NOT NULL COMMENT '딜러 이름',
  CELL_NUMBER    VARCHAR(200) NOT NULL COMMENT '전화번호',
  SALE           VARCHAR(200) NOT NULL COMMENT '판매중',
  SOLD_OUT       VARCHAR(200) NOT NULL COMMENT '판매완료',
  ACCIDENT_INFO  VARCHAR(200) NOT NULL COMMENT '사고 정보',
  CONTACT_DEALER varchar(300) NULL     COMMENT '1:1 상담요청',
  PRIMARY KEY (CAR_DTL_UID)
) COMMENT '차량 상세 정보';

CREATE TABLE MAIN_SKELETON
(
  SKELETON_UID VARCHAR(200) NOT NULL COMMENT '골격 아이디',
  FRONT_PANEL  VARCHAR(200) NOT NULL COMMENT '프론트 패널',
  CROSS_MEMBER VARCHAR(200) NOT NULL COMMENT '크로스 멤버',
  INSIDE_PANEL VARCHAR(200) NOT NULL COMMENT '인사이드 패널',
  SIDE_MEMBER  VARCHAR(200) NOT NULL COMMENT '사이드 멤버',
  WHEEL_HOUSE  VARCHAR(200) NOT NULL COMMENT '휠 하우스',
  PACKAGE_TRAY VARCHAR(200) NOT NULL COMMENT '패키지 트레이',
  DASH_PANEL   VARCHAR(200) NOT NULL COMMENT '대쉬 패널',
  FLOOR_PANEL  VARCHAR(200) NOT NULL COMMENT '플로어 패널',
  FILER_PANEL  VARCHAR(200) NOT NULL COMMENT '필러 패널',
  REAR_PANEL   VARCHAR(200) NOT NULL COMMENT '리어 패널',
  TRUNK_FLOOR  VARCHAR(200) NOT NULL COMMENT '트렁크 플로어',
  PRIMARY KEY (SKELETON_UID)
) COMMENT '주요 골격';

CREATE TABLE PANEL
(
  PANEL_UID     VARCHAR(200) NOT NULL COMMENT '패널 아이디',
  HOOD          VARCHAR(200) NOT NULL COMMENT '후드',
  FRONT_FENDER  VARCHAR(200) NOT NULL COMMENT '프론트휀더',
  DOOR          VARCHAR(200) NOT NULL COMMENT '도어',
  SIDE_PANEL    VARCHAR(200) NOT NULL COMMENT '사이드실패널',
  TRUNK_LID     VARCHAR(200) NOT NULL COMMENT '트렁크리드',
  ROOF_PANEL    VARCHAR(200) NOT NULL COMMENT '루프패널',
  QUARTER_PANEL VARCHAR(200) NOT NULL COMMENT '쿼터패널',
  PRIMARY KEY (PANEL_UID)
) COMMENT '외부 패널';

CREATE TABLE SIMULATION
(
  SIM_UID              VARCHAR(200) NOT NULL COMMENT '모의 계산아이디',
  VEHICLE_PRICE        VARCHAR(200) NOT NULL COMMENT '차량 가격',
  REGISTRATION_TAX     VARCHAR(200) NOT NULL COMMENT '등록세(5%)',
  ACQUISITION_TAX      VARCHAR(200) NOT NULL COMMENT '취득세(2%)',
  PUBLIC_PURCHASE_COST VARCHAR(200) NOT NULL COMMENT '공채매입비',
  INCREASE_RENT        VARCHAR(200) NOT NULL COMMENT '증지대',
  STAMP_DUTY           VARCHAR(200) NOT NULL COMMENT '인지대',
  TOTAL_PRICE          VARCHAR(200) NOT NULL COMMENT '총 가격',
  PRIMARY KEY (SIM_UID)
) COMMENT '할부금 모의 계산';

