
CREATE TABLE MYPAGE_MODIFY
(
  USER_UID      VARCHAR(200) NOT NULL COMMENT '회원정보 아이디',
  NAME          VARCHAR(200) NOT NULL COMMENT '이름',
  BIRTHDAY      VARCHAR(200) NOT NULL COMMENT '생년월일',
  ID            VARCHAR(200) NOT NULL COMMENT '아이디',
  PASSWORD      VARCHAR(200) NOT NULL COMMENT '비밀번호',
  CELL_NUMBER   VARCHAR(200) NULL     COMMENT '휴대번호',
  EMAIL         VARCHAR(200) NULL     COMMENT '이메일',
  ADDR_CITY     VARCHAR(200) NULL     COMMENT '주소',
  ADDR_DISTRICT VARCHAR(200) NULL     COMMENT '상세주소',
  PRIMARY KEY (USER_UID)
) COMMENT '회원정보 수정';
