
CREATE TABLE RESERVATION
(
  RESERVATION VARCHAR(45) NOT NULL COMMENT '예약 UID',
  USERID      VARCHAR(45) NOT NULL COMMENT '예약 유저 UID',
  PRICEID     VARCHAR(45) NOT NULL COMMENT '예약 상품 UID',
  DATE        DATE        NOT NULL COMMENT '예약 일자',
  PRIMARY KEY (RESERVATION)
) COMMENT '예약';
