
CREATE TABLE WISHLIST
(
  WISHLISTID VARCHAR(45) NOT NULL     COMMENT '찜 UID',
  USERID     VARCHAR(45) NOT NULL     COMMENT '찜 유저 UID',
  PRICEID    VARCHAR(45) NOT NULL     COMMENT '찜 상품 UID',
  PRIMARY KEY (WISHLISTID)
) COMMENT '찜목록';

