
CREATE TABLE MAIN_SEARCH
(
  MAIN_SEARCH_ID VARCHAR(200) NOT NULL COMMENT '메인검색ID',
  MANUFACTURER   VARCHAR(200) NULL     COMMENT '제조사',
  MODEL          VARCHAR(200) NULL     COMMENT '모델',
  DETAILED_MODEL VARCHAR(200) NULL     COMMENT '상세모델',
  DTL_IMG_CAR    VARCHAR(200) NULL     COMMENT '차량이미지',
  PRICE          INT          NULL     COMMENT '가격',
  MODEL_YEAR     VARCHAR(200) NULL     COMMENT '연식',
  DRIVEN_DIST    INT          NULL     COMMENT '주행거리',
  FUEL           VARCHAR(200) NULL     COMMENT '연료',
  ADDRESS        VARCHAR(200) NULL     COMMENT '지역',
  PRIMARY KEY (MAIN_SEARCH_ID)
) COMMENT '메인검색';
