-- 1. GET 방식 SELECT
SELECT CAR_ID, MANUFACTURER, DETAILED_MODEL, MODEL_YEAR, DRIVEN_DIST, FUEL FROM CAR_INFO;

-- 2. POST 방식 SELECT
SELECT CAR_ID, MANUFACTURER, DETAILED_MODEL, MODEL_YEAR, DRIVEN_DIST, FUEL FROM CAR_INFO
WHERE  MANUFACTURER ='현대' 
AND MODEL = '캐스퍼'
AND DRIVEN_DIST > 100000 
AND FUEL = '가솔린';