-- 1. GET 방식으로 받아올때 전체 SELECT
SELECT CAR_ID, MUNUFACTURER, DETAILED_MODEL, MODEL_YEAR, DRIVEN_DIST, FUEL FROM CAR_INFO;

-- 2. POST 방식으로 받아올때 SELECT
SELECT CAR_ID, MUNUFACTURER, DETAILED_MODEL, MODEL_YEAR, DRIVEN_DIST, FUEL FROM CAR_INFO
WHERE  MUNUFACTURER ='현대' 
AND MODEL = '캐스퍼'
AND DRIVEN_DIST > 100000 
AND FUEL = '가솔린';