
CREATE TABLE NOTICE_CONTENTS
(
  NOTICE_CONTENTS_ID   VARCHAR(200) NOT NULL COMMENT '공지사항내용ID',
  NOTICE_COTENTS_TITLE VARCHAR(200) NULL     COMMENT '공지사항내용제목',
  NOTICE_CONTENTS      VARCHAR(200) NULL     COMMENT '공지사항내용',
  PRIMARY KEY (NOTICE_CONTENTS_ID)
) COMMENT '공지사항내용';
