
CREATE TABLE NOTICE
(
  NOTICE_ID    VARCHAR(200) NOT NULL COMMENT '공지사항ID',
  NOTICE_NO    INT          NULL     COMMENT '공지사항번호',
  NOTICE_TITLE VARCHAR(200) NULL     COMMENT '공지사항제목',
  NOTICE_DATE  VARCHAR(200) NULL     COMMENT '공지사항등록일',
  PRIMARY KEY (NOTICE_ID)
) COMMENT '공지사항';
